"""baseline

Revision ID: 3778a8525828
Revises: 
Create Date: 2026-08-24 17:31:08.647284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3778a8525828'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_expires_at'), 'admin_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=True)
    op.create_table('game_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('lightning_collected', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_results_player_id'), 'game_results', ['player_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_entries_game_id'), 'leaderboard_entries', ['game_id'], unique=True)
    op.create_index(op.f('ix_leaderboard_entries_player_id'), 'leaderboard_entries', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_entries_player_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_game_id'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_game_results_player_id'), table_name='game_results')
    op.drop_table('game_results')
    op.drop_index(op.f('ix_admin_sessions_token_hash'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_expires_at'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
